#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_cwe_level_table.py

Purpose
-------
Generate a LocVul-style Top-10 CWE-level localization table from existing
Seq2Seq evaluation outputs. This script does NOT run the model again. It reads
per-seed *_details.csv files, joins each row back to the corresponding test set
so that CWE labels are available, and computes per-CWE line-level metrics.

Expected inputs
---------------
1) Evaluation details CSVs, usually generated by:
   seq2seq_eval_fixed_v3_compat_offline_v3_vulnonly.py
   Required columns in details files:
     row, gt_lines, pred_lines, ranked_topK, A@K, MRR@K, MAP@K, IFA
   P@K and R@K are recomputed from ranked_topK and gt_lines.

2) Either preprocessed test files:
     preprocessed_data_test_0.csv ... preprocessed_data_test_9.csv
   or dataset.csv, from which the fixed last-10% test split is reconstructed.
   Required dataset/test columns:
     processed_func, target, flaw_line, flaw_line_index, CWE ID
   The CWE column can also be named CWE, cwe, cwe_id, cwe_id/name, etc.

Outputs
-------
- cwe_level_per_seed_metrics.csv
- cwe_level_mean_std_metrics.csv
- cwe_level_top10_table.csv
- cwe_level_top10_table.md
- cwe_level_joined_details.csv  (optional, with --save_joined yes)

Example
-------
python make_cwe_level_table.py \
  --eval_outputs /home/tom/deeplearning/LocVul-main/nacgvuln_10seed/eval_outputs \
  --dataset_path /home/tom/deeplearning/LocVul-main/data/dataset.csv \
  --out_dir /home/tom/deeplearning/LocVul-main/paper_extra_results/cwe_level \
  --k 10 \
  --top_n 10
"""

from __future__ import annotations

import argparse
import ast
import math
import os
import re
import statistics
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd


METRIC_ORDER = [
    "A@10",
    "P@10",
    "R@10",
    "MRR@10",
    "MAP@10",
    "Median IFA",
    "Effort@20%Recall",
    "Recall@1%LOC",
]

CWE_CANDIDATE_COLUMNS = [
    "CWE ID",
    "CWE",
    "cwe",
    "cwe_id",
    "CWE_ID",
    "cwe-id",
    "cwe_id/name",
    "CWE-ID",
]

SEED_RE = re.compile(r"(?:^|[^0-9])seed[_-]?(\d+)(?:[^0-9]|$)", re.IGNORECASE)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate LocVul-style CWE-level localization metrics from evaluation details files."
    )
    parser.add_argument(
        "--eval_outputs",
        required=True,
        type=str,
        help="Directory containing per-seed *_details.csv files, or a single details CSV file.",
    )
    parser.add_argument(
        "--dataset_path",
        default=None,
        type=str,
        help="Path to data/dataset.csv. Used when --test_dir is absent or a seed test file is missing.",
    )
    parser.add_argument(
        "--test_dir",
        default=None,
        type=str,
        help="Directory containing preprocessed_data_test_{seed}.csv files. Optional.",
    )
    parser.add_argument(
        "--out_dir",
        required=True,
        type=str,
        help="Output directory for CWE-level CSV/Markdown tables.",
    )
    parser.add_argument("--k", default=10, type=int, help="Top-K value. Default: 10.")
    parser.add_argument("--top_n", default=10, type=int, help="Number of most frequent CWEs to report. Default: 10.")
    parser.add_argument(
        "--remove_missing_line_labels",
        default="yes",
        choices=["yes", "no"],
        help="Must match the evaluation setting. Default: yes.",
    )
    parser.add_argument(
        "--eval_only_vuln",
        default="yes",
        choices=["yes", "no"],
        help="Must match the evaluation setting. Default: yes.",
    )
    parser.add_argument(
        "--sort_by_lines",
        default="yes",
        choices=["yes", "no"],
        help="How to compute global effort metrics inside each CWE. Default: yes, same as your current protocol.",
    )
    parser.add_argument(
        "--details_glob",
        default="*_details.csv",
        type=str,
        help="Glob pattern under --eval_outputs. Default: *_details.csv.",
    )
    parser.add_argument(
        "--save_joined",
        default="yes",
        choices=["yes", "no"],
        help="Whether to save row-level details after joining CWE labels. Default: yes.",
    )
    return parser.parse_args()


def normalize_line(s: object) -> str:
    if s is None:
        return ""
    if isinstance(s, float) and math.isnan(s):
        return ""
    return " ".join(str(s).strip().split())


def split_locvul_lines(x: object) -> List[str]:
    """Parse line strings using LocVul-style /~/ delimiter or newline."""
    if x is None:
        return []
    if isinstance(x, float) and math.isnan(x):
        return []
    s = str(x).strip()
    if s == "" or s.lower() == "nan":
        return []
    if "/~/" in s:
        return [p.strip() for p in s.split("/~/") if p.strip()]
    if "\n" in s:
        return [p.strip() for p in s.splitlines() if p.strip()]
    return [s]


def parse_line_index_field(x: object) -> List[int]:
    """Robustly parse flaw_line_index into a list[int]."""
    if x is None:
        return []
    if isinstance(x, float) and math.isnan(x):
        return []
    if isinstance(x, (list, tuple, set)):
        out: List[int] = []
        for v in x:
            try:
                out.append(int(v))
            except Exception:
                pass
        return out

    s = str(x).strip()
    if s == "" or s.lower() == "nan":
        return []

    try:
        v = ast.literal_eval(s)
        if isinstance(v, (list, tuple, set)):
            out = []
            for item in v:
                try:
                    out.append(int(item))
                except Exception:
                    pass
            return out
        if isinstance(v, (int, np.integer)):
            return [int(v)]
    except Exception:
        pass

    # Fallback: extract all integer-like tokens.
    return [int(m.group()) for m in re.finditer(r"\d+", s)]


def find_cwe_column(df: pd.DataFrame) -> str:
    for c in CWE_CANDIDATE_COLUMNS:
        if c in df.columns:
            return c
    # Last fallback: any column containing cwe case-insensitively.
    for c in df.columns:
        if "cwe" in c.lower():
            return c
    raise ValueError(
        "未找到 CWE 列。请确认 dataset/test CSV 中存在 'CWE ID' 或类似列。"
    )


def canonicalize_cwe(x: object) -> str:
    """Normalize CWE values to strings such as CWE-119."""
    if x is None:
        return "UNKNOWN"
    if isinstance(x, float) and math.isnan(x):
        return "UNKNOWN"
    s = str(x).strip()
    if s == "" or s.lower() == "nan":
        return "UNKNOWN"

    # Typical cases: "CWE-119", "119", "['CWE-119']", "CWE-119/CWE-20".
    m = re.search(r"CWE[-_\s]?(\d+)", s, flags=re.IGNORECASE)
    if m:
        return f"CWE-{int(m.group(1))}"
    m = re.search(r"\b(\d{1,5})\b", s)
    if m:
        return f"CWE-{int(m.group(1))}"
    return s


def infer_seed_from_path(path: Path) -> Optional[int]:
    m = SEED_RE.search(path.name)
    if m:
        return int(m.group(1))
    m = SEED_RE.search(str(path.parent))
    if m:
        return int(m.group(1))
    return None


def discover_details_files(eval_outputs: Path, details_glob: str) -> List[Tuple[int, Path]]:
    if eval_outputs.is_file():
        seed = infer_seed_from_path(eval_outputs)
        if seed is None:
            raise ValueError(f"无法从 details 文件名推断 seed：{eval_outputs}")
        return [(seed, eval_outputs)]

    files = sorted(eval_outputs.rglob(details_glob))
    pairs: List[Tuple[int, Path]] = []
    for p in files:
        # Avoid accidentally reading joined output produced by this script.
        if "cwe_level_joined_details" in p.name:
            continue
        seed = infer_seed_from_path(p)
        if seed is None:
            print(f"[WARN] skip details without seed in path: {p}")
            continue
        pairs.append((seed, p))

    # If multiple details exist for the same seed, keep all; user may be aggregating variants intentionally.
    if not pairs:
        raise FileNotFoundError(f"在 {eval_outputs} 下没有找到可用的 {details_glob}")
    return pairs


def load_base_test_raw(seed: int, dataset_path: Optional[Path], test_dir: Optional[Path]) -> pd.DataFrame:
    """Load the raw test split before removing missing labels and target==0."""
    if test_dir is not None:
        test_path = test_dir / f"preprocessed_data_test_{seed}.csv"
        if test_path.exists():
            return pd.read_csv(test_path)
        print(f"[WARN] {test_path} 不存在，回退到 dataset.csv 的最后 10% 固定测试集。")

    if dataset_path is None:
        raise ValueError("既没有可用 --test_dir/preprocessed_data_test_{seed}.csv，也没有提供 --dataset_path。")
    if not dataset_path.exists():
        raise FileNotFoundError(f"dataset.csv 不存在：{dataset_path}")

    df = pd.read_csv(dataset_path)
    n = int(0.1 * len(df))
    if n <= 0:
        raise ValueError(f"dataset.csv 样本过少，无法取最后 10% 作为测试集：{len(df)}")
    return df.iloc[-n:, :].copy().reset_index(drop=True)


def prepare_test_data_for_eval(
    raw: pd.DataFrame,
    remove_missing_line_labels: str,
    eval_only_vuln: str,
) -> pd.DataFrame:
    required = ["processed_func", "target", "flaw_line", "flaw_line_index"]
    for c in required:
        if c not in raw.columns:
            raise ValueError(f"测试集缺少列：{c}")

    cwe_col = find_cwe_column(raw)
    out = pd.DataFrame(
        {
            "Text": raw["processed_func"],
            "target": raw["target"],
            "Lines": raw["flaw_line"],
            "Line_Index": raw["flaw_line_index"],
            "CWE": raw[cwe_col].apply(canonicalize_cwe),
        }
    )
    out["Line_Index_parsed"] = out["Line_Index"].apply(parse_line_index_field)
    if "proba" in raw.columns:
        out["proba"] = raw["proba"].astype(float)
    else:
        out["proba"] = 1.0

    if remove_missing_line_labels == "yes":
        miss = (
            (out["target"].astype(int) == 1)
            & (out["Lines"].isna() | out["Line_Index"].isna())
        )
        out = out.loc[~miss].reset_index(drop=True)

    if eval_only_vuln == "yes":
        out = out.loc[out["target"].astype(int) == 1].reset_index(drop=True)

    return out


def compute_p_r_at_k(gt_lines: List[str], ranked_lines: List[str], k: int) -> Tuple[float, float]:
    gt_norm = [normalize_line(x) for x in gt_lines if normalize_line(x)]
    gt_set = set(gt_norm)
    if not gt_set:
        return 0.0, 0.0

    ranked_top = ranked_lines[:k]
    hits = 0
    matched = set()
    for x in ranked_top:
        nx = normalize_line(x)
        if nx in gt_set:
            hits += 1
            matched.add(nx)
    precision = hits / k if k > 0 else 0.0
    recall = len(matched) / len(gt_set) if gt_set else 0.0
    return precision, recall


def build_full_ranked_lines(row: pd.Series) -> List[str]:
    """LocVul-style ranked list: predicted lines first, then remaining source lines in original order."""
    pred_lines = split_locvul_lines(row.get("pred_lines", ""))
    original_lines = str(row.get("Text", "")).splitlines()

    ranked: List[str] = []
    seen = set()
    for line in pred_lines:
        nl = normalize_line(line)
        if nl and nl not in seen:
            ranked.append(line)
            seen.add(nl)

    for line in original_lines:
        nl = normalize_line(line)
        if nl and nl not in seen:
            ranked.append(line)
            seen.add(nl)
    return ranked


def line_is_vulnerable_by_index_or_text(line_text: str, original_lines: List[str], true_indices: List[int], gt_lines: List[str]) -> int:
    """Return 1 if the ranked line corresponds to a vulnerable line."""
    nl = normalize_line(line_text)
    if not nl:
        return 0

    # Prefer index-based matching when line_index is available.
    if true_indices:
        norm_to_idxs: Dict[str, List[int]] = {}
        for idx, src_line in enumerate(original_lines):
            norm_to_idxs.setdefault(normalize_line(src_line), []).append(idx)
        for idx in norm_to_idxs.get(nl, []):
            if idx in true_indices:
                return 1

    # Fallback to text matching.
    gt_set = set(normalize_line(x) for x in gt_lines if normalize_line(x))
    return 1 if nl in gt_set else 0


def line_label_stream_for_subset(df: pd.DataFrame, sort_by_lines: str) -> Tuple[List[int], int, int]:
    """Build a global line-inspection stream for a CWE subset."""
    if df.empty:
        return [], 0, 0

    # If proba exists, mimic the original global ordering. Otherwise all values are 1.0.
    work = df.copy()
    if "proba" not in work.columns:
        work["proba"] = 1.0
    work = work.sort_values("proba", ascending=False, kind="mergesort")

    pred_stream: List[int] = []
    rest_stream: List[int] = []
    total_loc = 0
    total_vuln = 0

    for _, row in work.iterrows():
        original_lines = str(row.get("Text", "")).splitlines()
        gt_lines = split_locvul_lines(row.get("gt_lines", row.get("Lines", "")))
        true_indices = parse_line_index_field(row.get("Line_Index", ""))
        pred_norm = set(normalize_line(x) for x in split_locvul_lines(row.get("pred_lines", "")))
        ranked = build_full_ranked_lines(row)

        total_loc += max(1, len(original_lines))
        total_vuln += max(len(set(normalize_line(x) for x in gt_lines if normalize_line(x))), len(true_indices))

        for line in ranked:
            lab = line_is_vulnerable_by_index_or_text(line, original_lines, true_indices, gt_lines)
            if sort_by_lines == "yes":
                if normalize_line(line) in pred_norm:
                    pred_stream.append(lab)
                else:
                    rest_stream.append(lab)
            else:
                pred_stream.append(lab)

    stream = pred_stream + rest_stream if sort_by_lines == "yes" else pred_stream
    return stream, total_loc, total_vuln


def effort_at_20_recall_for_subset(df: pd.DataFrame, sort_by_lines: str) -> float:
    stream, total_loc, total_vuln = line_label_stream_for_subset(df, sort_by_lines)
    if not stream or total_loc <= 0 or total_vuln <= 0:
        return 0.0

    needed = max(1, int(math.ceil(0.2 * total_vuln)))
    inspected = 0
    found = 0
    for lab in stream:
        inspected += 1
        if lab == 1:
            found += 1
        if found >= needed:
            break
    inspected = min(inspected, total_loc)
    return inspected / total_loc


def recall_at_1pct_loc_for_subset(df: pd.DataFrame, sort_by_lines: str) -> float:
    stream, total_loc, total_vuln = line_label_stream_for_subset(df, sort_by_lines)
    if not stream or total_loc <= 0 or total_vuln <= 0:
        return 0.0

    budget = max(1, int(math.ceil(0.01 * total_loc)))
    found = sum(1 for lab in stream[:budget] if lab == 1)
    return found / total_vuln


def join_details_with_cwe(details_path: Path, test_data: pd.DataFrame, seed: int, k: int) -> pd.DataFrame:
    details = pd.read_csv(details_path)
    if details.empty:
        return pd.DataFrame()
    if "row" not in details.columns:
        details = details.copy()
        details["row"] = range(len(details))

    # Join against filtered test data by the local evaluation row index.
    meta_rows = []
    for _, r in details.iterrows():
        idx = int(r["row"])
        if idx < 0 or idx >= len(test_data):
            raise IndexError(
                f"{details_path} 中 row={idx} 超出过滤后测试集长度 {len(test_data)}。"
                "请确认 --remove_missing_line_labels 和 --eval_only_vuln 与评估脚本参数一致。"
            )
        t = test_data.iloc[idx]
        meta_rows.append(
            {
                "Text": t["Text"],
                "Lines": t["Lines"],
                "Line_Index": t["Line_Index"],
                "CWE": t["CWE"],
                "proba": t.get("proba", 1.0),
            }
        )
    meta = pd.DataFrame(meta_rows)

    joined = pd.concat([details.reset_index(drop=True), meta.reset_index(drop=True)], axis=1)
    joined["seed"] = seed
    joined["details_file"] = str(details_path)

    ranked_col = "ranked_topK" if "ranked_topK" in joined.columns else "ranked_lines_topK"
    if ranked_col not in joined.columns:
        raise ValueError(f"{details_path} 缺少 ranked_topK/ranked_lines_topK 列。")

    # Normalize core metric column names.
    if "A@K" in joined.columns:
        joined[f"A@{k}"] = joined["A@K"].astype(float)
    elif "accuracy" in joined.columns:
        joined[f"A@{k}"] = joined["accuracy"].astype(float)
    else:
        joined[f"A@{k}"] = 0.0

    if "MRR@K" in joined.columns:
        joined[f"MRR@{k}"] = joined["MRR@K"].astype(float)
    elif "MRR" in joined.columns:
        joined[f"MRR@{k}"] = joined["MRR"].astype(float)
    else:
        joined[f"MRR@{k}"] = 0.0

    if "MAP@K" in joined.columns:
        joined[f"MAP@{k}"] = joined["MAP@K"].astype(float)
    elif "MAP" in joined.columns:
        joined[f"MAP@{k}"] = joined["MAP"].astype(float)
    else:
        joined[f"MAP@{k}"] = 0.0

    # Recompute P@K and R@K row-wise.
    ps: List[float] = []
    rs: List[float] = []
    for _, row in joined.iterrows():
        gt_lines = split_locvul_lines(row.get("gt_lines", row.get("Lines", "")))
        ranked_lines = split_locvul_lines(row.get(ranked_col, ""))
        p, r = compute_p_r_at_k(gt_lines, ranked_lines, k)
        ps.append(p)
        rs.append(r)
    joined[f"P@{k}"] = ps
    joined[f"R@{k}"] = rs

    if "IFA" not in joined.columns:
        joined["IFA"] = np.nan
    joined["loc"] = joined.get("loc", joined["Text"].apply(lambda x: max(1, len(str(x).splitlines()))))
    joined["n_gt_lines"] = joined.get("n_gt_lines", joined["gt_lines"].apply(lambda x: len(split_locvul_lines(x))))

    return joined


def aggregate_per_seed(joined: pd.DataFrame, k: int, sort_by_lines: str) -> pd.DataFrame:
    rows: List[dict] = []
    if joined.empty:
        return pd.DataFrame()

    for (seed, cwe), g in joined.groupby(["seed", "CWE"], sort=False):
        row = {
            "seed": int(seed),
            "CWE": cwe,
            "support_functions": int(len(g)),
            "support_vuln_lines": int(g["n_gt_lines"].fillna(0).sum()) if "n_gt_lines" in g.columns else 0,
            f"A@{k}": float(g[f"A@{k}"].mean()),
            f"P@{k}": float(g[f"P@{k}"].mean()),
            f"R@{k}": float(g[f"R@{k}"].mean()),
            f"MRR@{k}": float(g[f"MRR@{k}"].mean()),
            f"MAP@{k}": float(g[f"MAP@{k}"].mean()),
            "Median IFA": float(g["IFA"].median()) if "IFA" in g.columns else 0.0,
            "Effort@20%Recall": effort_at_20_recall_for_subset(g, sort_by_lines),
            "Recall@1%LOC": recall_at_1pct_loc_for_subset(g, sort_by_lines),
        }
        rows.append(row)
    return pd.DataFrame(rows)


def mean_safe(vals: Iterable[float]) -> float:
    arr = [float(x) for x in vals if pd.notna(x)]
    return float(sum(arr) / len(arr)) if arr else 0.0


def std_safe(vals: Iterable[float]) -> float:
    arr = [float(x) for x in vals if pd.notna(x)]
    return float(statistics.stdev(arr)) if len(arr) > 1 else 0.0


def aggregate_mean_std(per_seed: pd.DataFrame, k: int) -> pd.DataFrame:
    metrics = [
        f"A@{k}",
        f"P@{k}",
        f"R@{k}",
        f"MRR@{k}",
        f"MAP@{k}",
        "Median IFA",
        "Effort@20%Recall",
        "Recall@1%LOC",
    ]
    rows: List[dict] = []
    for cwe, g in per_seed.groupby("CWE", sort=False):
        row = {
            "CWE": cwe,
            "n_seeds": int(g["seed"].nunique()),
            "support_functions_mean": mean_safe(g["support_functions"]),
            "support_functions_min": int(g["support_functions"].min()),
            "support_functions_max": int(g["support_functions"].max()),
            "support_vuln_lines_mean": mean_safe(g["support_vuln_lines"]),
        }
        for m in metrics:
            row[f"{m}_mean"] = mean_safe(g[m])
            row[f"{m}_std"] = std_safe(g[m])
        rows.append(row)

    out = pd.DataFrame(rows)
    out = out.sort_values(["support_functions_mean", "CWE"], ascending=[False, True]).reset_index(drop=True)
    return out


def fmt_percent_mean_std(mean: float, std: float) -> str:
    return f"{mean * 100:.2f}±{std * 100:.2f}"


def fmt_number_mean_std(mean: float, std: float) -> str:
    if abs(std) < 1e-12:
        return f"{mean:.2f}"
    return f"{mean:.2f}±{std:.2f}"


def build_top_table(mean_std: pd.DataFrame, k: int, top_n: int) -> pd.DataFrame:
    top = mean_std.head(top_n).copy()
    rows: List[dict] = []
    percent_metrics = [f"A@{k}", f"P@{k}", f"R@{k}", f"MRR@{k}", f"MAP@{k}", "Effort@20%Recall", "Recall@1%LOC"]
    for _, r in top.iterrows():
        row = {
            "CWE": r["CWE"],
            "#Functions": int(round(float(r["support_functions_mean"]))),
            "#VulnLines": int(round(float(r["support_vuln_lines_mean"]))),
        }
        for m in percent_metrics:
            row[m] = fmt_percent_mean_std(float(r[f"{m}_mean"]), float(r[f"{m}_std"]))
        row["Median IFA"] = fmt_number_mean_std(float(r["Median IFA_mean"]), float(r["Median IFA_std"]))
        rows.append(row)
    return pd.DataFrame(rows)


def dataframe_to_markdown(df: pd.DataFrame, title: str) -> str:
    lines = [f"# {title}", ""]
    if df.empty:
        lines.append("空表。")
        return "\n".join(lines) + "\n"
    headers = list(df.columns)
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] + ["---:" for _ in headers[1:]]) + " |")
    for _, r in df.iterrows():
        vals = [str(r[c]) for c in headers]
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    eval_outputs = Path(args.eval_outputs)
    dataset_path = Path(args.dataset_path) if args.dataset_path else None
    test_dir = Path(args.test_dir) if args.test_dir else None
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    details_pairs = discover_details_files(eval_outputs, args.details_glob)
    print(f"[INFO] found {len(details_pairs)} details files")

    all_joined: List[pd.DataFrame] = []
    for seed, details_path in details_pairs:
        raw_test = load_base_test_raw(seed, dataset_path, test_dir)
        test_data = prepare_test_data_for_eval(
            raw_test,
            remove_missing_line_labels=args.remove_missing_line_labels,
            eval_only_vuln=args.eval_only_vuln,
        )
        joined = join_details_with_cwe(details_path, test_data, seed, args.k)
        print(
            f"[OK] seed={seed} rows={len(joined)} cwes={joined['CWE'].nunique() if not joined.empty else 0} file={details_path}"
        )
        all_joined.append(joined)

    if not all_joined:
        raise RuntimeError("没有可聚合的 details。")
    joined_df = pd.concat(all_joined, ignore_index=True)

    if args.save_joined == "yes":
        joined_path = out_dir / "cwe_level_joined_details.csv"
        joined_df.to_csv(joined_path, index=False)
        print(f"[SAVE] {joined_path}")

    per_seed = aggregate_per_seed(joined_df, args.k, args.sort_by_lines)
    per_seed_path = out_dir / "cwe_level_per_seed_metrics.csv"
    per_seed.to_csv(per_seed_path, index=False)
    print(f"[SAVE] {per_seed_path}")

    mean_std = aggregate_mean_std(per_seed, args.k)
    mean_std_path = out_dir / "cwe_level_mean_std_metrics.csv"
    mean_std.to_csv(mean_std_path, index=False)
    print(f"[SAVE] {mean_std_path}")

    top_table = build_top_table(mean_std, args.k, args.top_n)
    top_csv_path = out_dir / "cwe_level_top10_table.csv"
    top_md_path = out_dir / "cwe_level_top10_table.md"
    top_table.to_csv(top_csv_path, index=False)
    top_md_path.write_text(
        dataframe_to_markdown(top_table, f"Top-{args.top_n} CWE-level localization results"),
        encoding="utf-8",
    )
    print(f"[SAVE] {top_csv_path}")
    print(f"[SAVE] {top_md_path}")

    print("\n[DONE] CWE-level table generated.")
    print(f"Top table preview:\n{top_table.to_string(index=False)}")


if __name__ == "__main__":
    main()
